# Generated by Django 5.2.5 on 2025-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_instruction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
