# Generated by Django 5.2.5 on 2025-08-14 03:28

import apps.recipes.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(help_text="Enter a number or fraction like '1/2' or '2 1/2'", max_length=20, validators=[apps.recipes.validators.validate_quantity_format, apps.recipes.validators.validate_quantity]),
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='recipes.cuisine')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisines',
            field=models.ManyToManyField(to='recipes.cuisine'),
        ),
    ]
