# Generated by Django 5.2.5 on 2025-08-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredient_quantity_cuisine_recipe_cuisines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('c', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('fl', 'Fluid ounce'), ('oz', 'Ounce'), ('lb', 'Pound'), ('dash', '1/8 teaspoon'), ('pinch', 'Pinch'), ('stick', 'Stick'), ('mL', 'Milliliter'), ('L', 'Liter'), ('kg', 'Kilogram'), ('g', 'Gram')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
