# Generated by Django 5.2.5 on 2025-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_cuisine_options_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'name'), name='unique_ingredient_per_recipe'),
        ),
    ]
