# Generated by Django 5.2.5 on 2025-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
