# Generated by Django 5.2.4 on 2025-08-04 00:39

import apps.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[apps.recipes.validators.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('c', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('fl', 'Fluid ounce'), ('oz', 'Ounce'), ('lb', 'Pound'), ('dash', '1/8 teaspoon'), ('pinch', 'Pinch'), ('stick', 'Stick'), ('mL', 'Milliliter'), ('L', 'Liter'), ('kg', 'Kilogram'), ('g', 'Gram')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=models.TextField(validators=[apps.recipes.validators.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[apps.recipes.validators.validate_no_profanity]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, validators=[apps.recipes.validators.validate_no_profanity]),
        ),
    ]
