# Generated by Django 5.2.4 on 2025-08-04 00:49

import apps.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_name_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, validators=[apps.recipes.validators.validate_no_profanity]),
        ),
    ]
