# Generated by Django 5.2.5 on 2025-08-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_instruction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(help_text="e.g., '1', '1/2', '2 1/2", max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('fl', 'Fluid ounce'), ('oz', 'Ounce'), ('lb', 'Pound'), ('dash', '1/8 teaspoon'), ('pinch', 'Pinch'), ('stick', 'Stick'), ('mL', 'Milliliter'), ('Liter', 'Liter'), ('kg', 'Kilogram'), ('gram', 'Gram')], max_length=10, null=True),
        ),
    ]
