# Generated by Django 5.2.5 on 2025-08-10 13:26

import apps.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(help_text="e.g., '1', '1/2', '2 1/2", max_length=20, validators=[apps.recipes.validators.validate_quantity_format]),
        ),
    ]
