# Generated by Django 5.2.5 on 2025-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
