# Generated by Django 5.2.5 on 2025-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_instruction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('c', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('fl', 'Fluid ounce'), ('oz', 'Ounce'), ('lb', 'Pound'), ('dash', '1/8 teaspoon'), ('pinch', 'Pinch'), ('stick', 'Stick'), ('mL', 'Milliliter'), ('L', 'Liter'), ('kg', 'Kilogram'), ('g', 'Gram')], max_length=10, null=True),
        ),
    ]
