name: Django CI with uv to Render

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true  
      DEBUG: true 
      SECRET_KEY: test-secret-key
      ALLOWED_HOSTS: localhost,127.0.0.1
      CORS_ALLOWED_ORIGINS: http://localhost,http://127.0.0.1
      CORS_ALLOW_METHODS: GET,POST,PUT,PATCH,DELETE,OPTIONS
      CORS_ALLOW_HEADERS: accept,accept-encoding,authorization,content-type,dnt,origin,user-agent,x-csrftoken,x-requested-with

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        shell: bash

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: uv sync

      - name: Copy CI env
        run: cp .env.ci .env

      - name: Run migrations
        run: uv run python manage.py migrate

      - name: Run tests
        run: uv run python manage.py test
